name: Build Check

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm ci

            - name: Install Lune
              run: |
                  curl -L https://github.com/filiptibell/lune/releases/latest/download/lune-linux-x86_64.tar.gz | tar -xz
                  sudo mv lune /usr/local/bin/lune

            - name: Build TypeScript
              run: npm run build

            - name: Assemble Place
              run: lune run lune/assemble.luau

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: place-rbxl
                  path: place.rbxl
